services:
  # FEDEVENT Prelaunch Server
  - type: web
    name: fedevent-prelaunch
    runtime: node
    buildCommand: npm install
    startCommand: node prelaunch-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 465
      - key: SMTP_SECURE
        value: true
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: NOTIFY_TO
        sync: false
      - key: NOTIFY_FROM
        value: noreply@fedevent.com
